### ISSUE TITLE
Support for nested configurations

### ISSUE THREAD

**Issue by lubieniebieski** [netguru/app_konfig#2]
it would be very helpful to have nested configuration working, like `AppConfig.emails.office`

**Comment by mic-kul** [comment]
:+1:
there is ugly workaround: `AppConfig.emails['office']`

**Comment by nekath** [comment]
The problem is that at some keys we get hash instead of OrderedOptions object.

**Comment by nekath** [comment]
Fixed in https://github.com/netguru/app_konfig/pull/3

Closing.
